export const FETCHING_SIGNIN_ACCOUNT = "FETCHING_SIGNIN_ACCOUNT";
export const SUCCESS_SIGNIN_ACCOUNT = "SUCCESS_SIGNIN_ACCOUNT";
export const FAILED_SIGNIN_ACCOUNT = "FAILED_SIGNIN_ACCOUNT";
export const CLEAR_SIGNIN_ACCOUNT = "CLEAR_SIGNIN_ACCOUNT";

export const FETCHING_SIGNUP_ACCOUNT = "FETCHING_SIGNUP_ACCOUNT";
export const SUCCESS_SIGNUP_ACCOUNT = "SUCCESS_SIGNUP_ACCOUNT";
export const FAILED_SIGNUP_ACCOUNT = "FAILED_SIGNUP_ACCOUNT";
export const CLEAR_SIGNUP_ACCOUNT = "CLEAR_SIGNUP_ACCOUNT";

export const FETCHING_VERIFY_EMAIL_ACCOUNT = "FETCHING_VERIFY_EMAIL_ACCOUNT";
export const SUCCESS_VERIFY_EMAIL_ACCOUNT = "SUCCESS_VERIFY_EMAIL_ACCOUNT";
export const FAILED_VERIFY_EMAIL_ACCOUNT = "FAILED_VERIFY_EMAIL_ACCOUNT";

export const FETCHING_CHANGE_ROLE = "FETCHING_CHANGE_ROLE";
export const SUCCESS_CHANGE_ROLE = "SUCCESS_CHANGE_ROLE";
export const FAILED_CHANGE_ROLE = "FAILED_CHANGE_ROLE";

export const FETCHING_DELETE_ACCOUNT = "FETCHING_DELETE_ACCOUNT";
export const SUCCESS_DELETE_ACCOUNT = "SUCCESS_DELETE_ACCOUNT";
export const FAILED_DELETE_ACCOUNT = "FAILED_DELETE_ACCOUNT";
