export const SUCCESS_DETAIL_ARTICLE = "SUCCESS_DETAIL_ARTICLE";
export const FAILED_DETAIL_ARTICLE = "FAILED_DETAIL_ARTICLE";
export const CLEAR_DETAIL_ARTICLE = "CLEAR_DETAIL_ARTICLE";

export const FETCHING_ADD_ARTICLE = "FETCHING_ADD_ARTICLE";
export const SUCCESS_ADD_ARTICLE = "SUCCESS_ADD_ARTICLE";
export const FAILED_ADD_ARTICLE = "FAILED_ADD_ARTICLE";
export const CLEAR_ADD_ARTICLE = "CLEAR_ADD_ARTICLE";

export const FETCHING_EDIT_ARTICLE = "FETCHING_EDIT_ARTICLE";
export const SUCCESS_EDIT_ARTICLE = "SUCCESS_EDIT_ARTICLE";
export const FAILED_EDIT_ARTICLE = "FAILED_EDIT_ARTICLE";
export const CLEAR_EDIT_ARTICLE = "CLEAR_EDIT_ARTICLE";

export const FETCHING_GET_ALL_ARTICLE = "FETCHING_GET_ALL_ARTICLE";
export const SUCCESS_GET_ALL_ARTICLE = "SUCCESS_GET_ALL_ARTICLE";
export const FAILED_GET_ALL_ARTICLE = "FAILED_GET_ALL_ARTICLE";

export const FETCHING_DELETE_ARTICLE = "FETCHING_DELETE_ARTICLE";
export const SUCCESS_DELETE_ARTICLE = "SUCCESS_DELETE_ARTICLE";
export const FAILED_DELETE_ARTICLE = "FAILED_DELETE_ARTICLE";

export const SUCCESS_ARTICLE_ANALYSIS = "SUCCESS_ARTICLE_ANALYSIS";
export const FAILED_ARTICLE_ANALYSIS = "FAILED_ARTICLE_ANALYSIS";

export const FETCHING_GET_ALL_USERS = "FETCHING_GET_ALL_USERS";
export const SUCCESS_GET_ALL_USERS = "SUCCESS_GET_ALL_USERS";
export const FAILED_GET_ALL_USERS = "FAILED_GET_ALL_USERS";

export const SUCCESS_GET_ALL_USERS_CONFIG = "SUCCESS_GET_ALL_USERS_CONFIG";
export const FAILED_GET_ALL_USERS_CONFIG = "FAILED_GET_ALL_USERS_CONFIG";
