// topics
export const RELOG_ERROR_TOPICS = "RELOG_ERROR_TOPICS";
export const SUCCESS_GET_TOPICS = "SUCCESS_GET_TOPICS";
export const FAILED_GET_TOPICS = "FAILED_GET_TOPICS";

// trending
export const RELOG_ERROR_TRENDING = "RELOG_ERROR_TRENDING";
export const SUCCESS_GET_TRENDING = "SUCCESS_GET_TRENDING";
export const FAILED_GET_TRENDING = "FAILED_GET_TRENDING";

// search term
export const FETCHING_SEARCHTERM = "FETCHING_SEARCHTERM";
export const SUCCESS_GET_SEARCHTERM = "SUCCESS_GET_SEARCHTERM";
export const FAILED_GET_SEARCHTERM = "FAILED_GET_SEARCHTERM";
export const CLEAR_SEARCHTERM = "CLEAR_SEARCHTERM";

// search term history
export const SUCCESS_GET_SEARCHTERM_HISTORY = "SUCCESS_GET_SEARCHTERM_HISTORY";
export const FAILED_GET_SEARCHTERM_HISTORY = "FAILED_GET_SEARCHTERM_HISTORY";

// search result
export const SUCCESS_GET_SEARCHRESULT = "SUCCESS_GET_SEARCHRESULT";
export const FAILED_GET_SEARCHRESULT = "FAILED_GET_SEARCHRESULT";
export const CLEAR_SEARCHRESULT = "CLEAR_SEARCHRESULT";

// detail article
export const SUCCESS_GET_DETAIL_ARTICLE = "SUCCESS_GET_DETAIL_ARTICLE";
export const FAILED_GET_DETAIL_ARTICLE = "FAILED_GET_DETAIL_ARTICLE";
export const CLEAR_DETAIL_ARTICLE = "CLEAR_DETAIL_ARTICLE";

// foryo article
export const RELOG_ERROR_FORYOU_ARTICLE = "RELOG_ERROR_FORYOU_ARTICLE";
export const SUCCESS_GET_FORYOU_ARTICLE = "SUCCESS_GET_FORYOU_ARTICLE";
export const FAILED_GET_FORYOU_ARTICLE = "FAILED_GET_FORYOU_ARTICLE";

// foryo article
export const RELOG_ERROR_BY_TOPICS_ARTICLE = "RELOG_ERROR_BY_TOPICS_ARTICLE";
export const SUCCESS_GET_BY_TOPICS_ARTICLE = "SUCCESS_GET_BY_TOPICS_ARTICLE";
export const FAILED_GET_BY_TOPICS_ARTICLE = "FAILED_GET_BY_TOPICS_ARTICLE";
export const CLEAR_BY_TOPICS_ARTICLE = "CLEAR_BY_TOPICS_ARTICLE";

// article report
export const FETCHING_ADD_REPORT = "FETCHING_ADD_REPORT";
export const SUCCESS_ADD_REPORT = "SUCCESS_ADD_REPORT";
export const FAILED_ADD_REPORT = "FAILED_ADD_REPORT";
export const CLEAR_ADD_REPORT = "CLEAR_ADD_REPORT";

// article not intersed
export const FETCHING_NOT_INTERESTED = "FETCHING_NOT_INTERESTED";
export const SUCCESS_NOT_INTERESTED = "SUCCESS_NOT_INTERESTED";
export const FAILED_NOT_INTERESTED = "FAILED_NOT_INTERESTED";

// short link
export const SUCCESS_SHORT_LINK_ARTICLE = "SUCCESS_SHORT_LINK_ARTICLE";
export const FAILED_SHORT_LINK_ARTICLE = "FAILED_SHORT_LINK_ARTICLE";

// user
export const SUCCESS_USER = "SUCCESS_USER";
export const FAILED_USER = "FAILED_USER";
export const CLEAR_USER = "CLEAR_USER";

// article by user
export const FETCHING_ARTICLE_USER = "FETCHING_ARTICLE_USER";
export const SUCCESS_ARTICLE_USER = "SUCCESS_ARTICLE_USER";
export const FAILED_ARTICLE_USER = "FAILED_ARTICLE_USER";
