export const SUCCESS_GET_PROFILE_USER = "SUCCESS_GET_PROFILE_USER";
export const FAILED_GET_PROFILE_USER = "FAILED_GET_PROFILE_USER";

// get role
export const SUCCESS_GET_ROLE = "SUCCESS_GET_ROLE";
export const FAILED_GET_ROLE = "FAILED_GET_ROLE";
